
import React, { useState } from 'react';
import { Reel } from '../types';

const INITIAL_REELS: Reel[] = [
  {
    id: '1',
    url: 'https://assets.mixkit.co/videos/preview/mixkit-girl-in-neon-lighting-sitting-at-a-bar-34674-large.mp4',
    title: 'Cyberpunk Vibes',
    author: 'neon_dreams',
    likes: 1240,
    comments: 89,
    description: 'Welcome to the future of content. #ai #cyberpunk #future',
    isLiked: false,
    isSaved: false
  },
  {
    id: '2',
    url: 'https://assets.mixkit.co/videos/preview/mixkit-set-of-plateaus-seen-from-the-height-of-a-mountain-44371-large.mp4',
    title: 'Nature Unleashed',
    author: 'wild_explorer',
    likes: 850,
    comments: 45,
    description: 'Breathtaking views generated by AI. Experience the serenity. #nature #travel #peace',
    isLiked: true,
    isSaved: false
  }
];

const Feed: React.FC = () => {
  const [reels, setReels] = useState<Reel[]>(INITIAL_REELS);

  const toggleLike = (id: string) => {
    setReels(prev => prev.map(r => r.id === id ? { ...r, isLiked: !r.isLiked, likes: r.isLiked ? r.likes - 1 : r.likes + 1 } : r));
  };

  const toggleSave = (id: string) => {
    setReels(prev => prev.map(r => r.id === id ? { ...r, isSaved: !r.isSaved } : r));
  };

  return (
    <div className="h-full flex flex-col">
      {/* Stories Bar */}
      <div className="flex gap-4 p-4 overflow-x-auto no-scrollbar border-b border-white/5 bg-slate-950/50">
        <StoryItem label="Your Story" isUser />
        <StoryItem label="tech_guru" />
        <StoryItem label="pixel_art" />
        <StoryItem label="ai_daily" />
        <StoryItem label="synth_wave" />
        <StoryItem label="retro_vibe" />
      </div>

      {/* Reels Feed */}
      <div className="flex-1 snap-y snap-mandatory overflow-y-scroll no-scrollbar">
        {reels.map(reel => (
          <div key={reel.id} className="relative h-full w-full snap-start bg-black flex items-center justify-center overflow-hidden">
            <video 
              src={reel.url} 
              className="h-full w-full object-cover" 
              autoPlay 
              muted 
              loop 
              playsInline
            />
            
            {/* Interactive Overlay */}
            <div className="absolute inset-0 bg-gradient-to-b from-black/20 via-transparent to-black/80 flex flex-col justify-end">
              <div className="flex p-5 items-end justify-between w-full">
                {/* Text Content */}
                <div className="flex-1 mr-12 space-y-3">
                  <div className="flex items-center gap-2">
                    <div className="w-9 h-9 rounded-full bg-slate-800 border border-teal-500/30 overflow-hidden">
                      <img src={`https://api.dicebear.com/7.x/avataaars/svg?seed=${reel.author}`} alt="avatar" />
                    </div>
                    <span className="font-bold text-sm">@{reel.author}</span>
                    <button className="px-3 py-1 border border-white/20 rounded-lg text-xs font-bold hover:bg-white/10 transition">Follow</button>
                  </div>
                  <p className="text-sm text-slate-100 line-clamp-2 leading-relaxed">{reel.description}</p>
                  <div className="flex items-center gap-2 text-xs font-medium text-teal-400 bg-teal-400/10 w-fit px-2 py-1 rounded-full">
                    <i className="fa-solid fa-music animate-pulse"></i>
                    <span className="truncate max-w-[150px]">Original AI Sound - {reel.title}</span>
                  </div>
                </div>
                
                {/* Side Actions */}
                <div className="flex flex-col items-center gap-5 mb-2">
                  <ActionBtn 
                    icon={reel.isLiked ? "fa-solid fa-heart text-red-500 scale-110" : "fa-regular fa-heart"} 
                    count={reel.likes} 
                    onClick={() => toggleLike(reel.id)}
                  />
                  <ActionBtn icon="fa-regular fa-comment" count={reel.comments} />
                  <ActionBtn icon="fa-regular fa-paper-plane" count={0} hideCount />
                  <ActionBtn 
                    icon={reel.isSaved ? "fa-solid fa-bookmark text-teal-400" : "fa-regular fa-bookmark"} 
                    count={0} 
                    hideCount 
                    onClick={() => toggleSave(reel.id)}
                  />
                  <div className="w-8 h-8 rounded-full border-2 border-white/40 overflow-hidden animate-spin-slow">
                    <div className="w-full h-full bg-slate-700 flex items-center justify-center">
                      <i className="fa-solid fa-compact-disc text-slate-400"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

const StoryItem = ({ label, isUser }: { label: string; isUser?: boolean }) => (
  <div className="flex flex-col items-center gap-1 shrink-0">
    <div className={`w-16 h-16 rounded-full flex items-center justify-center p-[2px] ${isUser ? 'bg-slate-800' : 'btn-gradient p-[2px]'}`}>
      <div className="w-full h-full rounded-full bg-slate-950 border-2 border-slate-950 overflow-hidden relative">
        <img src={`https://api.dicebear.com/7.x/avataaars/svg?seed=${label}`} alt="avatar" />
        {isUser && (
          <div className="absolute bottom-0 right-0 bg-teal-500 w-5 h-5 rounded-full border-2 border-slate-950 flex items-center justify-center">
            <i className="fa-solid fa-plus text-[8px] text-white"></i>
          </div>
        )}
      </div>
    </div>
    <span className="text-[10px] text-slate-400 max-w-[64px] truncate">{label}</span>
  </div>
);

const ActionBtn = ({ icon, count, onClick, hideCount }: { icon: string; count: number; onClick?: () => void; hideCount?: boolean }) => (
  <div className="flex flex-col items-center gap-1">
    <button onClick={onClick} className="text-2xl drop-shadow-lg transition-transform active:scale-125">
      <i className={icon}></i>
    </button>
    {!hideCount && <span className="text-xs font-bold drop-shadow-md">{count}</span>}
  </div>
);

export default Feed;
