
import React, { useState } from 'react';
import { Reel, PostComment } from '../types';

const INITIAL_REELS: Reel[] = [
  {
    id: 'r1',
    url: 'https://assets.mixkit.co/videos/preview/mixkit-girl-in-neon-lighting-sitting-at-a-bar-34674-large.mp4',
    title: 'Neon Dreams',
    author: 'ai_visionary',
    likes: 4200,
    comments: 152,
    description: 'The night is young and full of lights. Generated by Veo 3.1. #cyberpunk #neon',
    isLiked: false
  },
  {
    id: 'r2',
    url: 'https://assets.mixkit.co/videos/preview/mixkit-set-of-plateaus-seen-from-the-height-of-a-mountain-44371-large.mp4',
    title: 'Highlands',
    author: 'world_builder',
    likes: 890,
    comments: 42,
    description: 'Majestic landscapes from another world. #aiart #landscape',
    isLiked: false
  }
];

const ReelsFeed: React.FC<{ userAssets?: Reel[], currentUser?: string }> = ({ userAssets = [], currentUser = 'reelzy_pioneer' }) => {
  const allReels = [...userAssets, ...INITIAL_REELS];
  const [reels, setReels] = useState<Reel[]>(allReels);
  const [activeSheet, setActiveSheet] = useState<{ type: 'comments' | 'share' | 'more', reelId: string } | null>(null);
  const [commentText, setCommentText] = useState('');
  const [reelComments, setReelComments] = useState<Record<string, PostComment[]>>({});

  const toggleLike = (id: string) => {
    setReels(prev => prev.map(r => r.id === id ? { ...r, isLiked: !r.isLiked, likes: r.isLiked ? r.likes - 1 : r.likes + 1 } : r));
  };

  const addComment = () => {
    if (!commentText.trim() || !activeSheet) return;
    const newComment: PostComment = {
      id: Math.random().toString(),
      user: currentUser,
      text: commentText,
      time: 'Just now',
      avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=${currentUser}`
    };
    setReelComments(prev => ({
      ...prev,
      [activeSheet.reelId]: [newComment, ...(prev[activeSheet.reelId] || [])]
    }));
    setCommentText('');
  };

  return (
    <div className="h-full w-full snap-y snap-mandatory overflow-y-scroll no-scrollbar bg-black text-white relative">
      {reels.map(reel => (
        <div key={reel.id} className="relative h-full w-full snap-start flex items-center justify-center overflow-hidden">
          <video 
            src={reel.url} 
            className="h-full w-full object-cover" 
            autoPlay 
            muted 
            loop 
            playsInline
          />
          
          <div className="absolute inset-0 bg-gradient-to-b from-black/30 via-transparent to-black/80 flex flex-col justify-end">
            <div className="flex p-5 pb-8 items-end justify-between w-full">
              <div className="flex-1 mr-12 space-y-3">
                <div className="flex items-center gap-2">
                  <div className="w-10 h-10 rounded-full bg-slate-800 border-2 border-white/20 overflow-hidden">
                    <img src={`https://api.dicebear.com/7.x/avataaars/svg?seed=${reel.author}`} alt="avatar" />
                  </div>
                  <span className="font-bold text-base drop-shadow-md text-white">@{reel.author}</span>
                  <button className="px-4 py-1.5 bg-white/20 border border-white/30 rounded-lg text-xs font-bold text-white backdrop-blur-sm active:scale-95 transition-transform">Follow</button>
                </div>
                <p className="text-sm text-white/90 line-clamp-2 leading-relaxed drop-shadow-md font-medium">{reel.description}</p>
                <div className="flex items-center gap-2 text-xs font-bold text-white bg-white/10 w-fit px-3 py-1.5 rounded-full backdrop-blur-md border border-white/5">
                  <i className="fa-solid fa-music"></i>
                  <span className="truncate max-w-[150px]">Gemini Original Audio • {reel.title}</span>
                </div>
              </div>
              
              <div className="flex flex-col items-center gap-5 mb-2">
                <ReelAction 
                  icon={reel.isLiked ? "fa-solid fa-heart text-[#FF3040]" : "fa-solid fa-heart"} 
                  count={reel.likes} 
                  onClick={() => toggleLike(reel.id)} 
                />
                <ReelAction 
                  icon="fa-solid fa-comment" 
                  count={reel.comments + (reelComments[reel.id]?.length || 0)} 
                  onClick={() => setActiveSheet({ type: 'comments', reelId: reel.id })}
                />
                <ReelAction 
                  icon="fa-solid fa-paper-plane" 
                  count={0} 
                  hideCount 
                  onClick={() => setActiveSheet({ type: 'share', reelId: reel.id })}
                />
                <ReelAction 
                  icon="fa-solid fa-ellipsis" 
                  count={0} 
                  hideCount 
                  onClick={() => setActiveSheet({ type: 'more', reelId: reel.id })}
                />
                
                <div className="w-9 h-9 rounded-full border-2 border-white/40 p-1 animate-[spin_3s_linear_infinite]">
                   <div className="w-full h-full bg-zinc-800 rounded-full flex items-center justify-center">
                     <i className="fa-solid fa-compact-disc text-[10px] text-white/60"></i>
                   </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      ))}

      {/* Reels Interaction Sheets */}
      {activeSheet && (
        <div className="fixed inset-0 z-[150] flex flex-col justify-end">
          <div className="absolute inset-0 bg-black/40" onClick={() => setActiveSheet(null)} />
          
          <div className="relative bg-white dark:bg-[#262626] text-black dark:text-white rounded-t-xl overflow-hidden animate-in slide-in-from-bottom-full duration-300 max-h-[70vh] flex flex-col">
            <div className="w-9 h-1 bg-gray-500/30 rounded-full mx-auto my-3 shrink-0"></div>
            
            {activeSheet.type === 'comments' && (
              <div className="flex-1 flex flex-col overflow-hidden">
                <div className="text-center font-bold border-b dark:border-white/10 pb-3 shrink-0">Comments</div>
                <div className="flex-1 overflow-y-auto p-4 space-y-5">
                  {(reelComments[activeSheet.reelId] || []).map(comment => (
                    <CommentItem key={comment.id} comment={comment} />
                  ))}
                  <div className="text-center py-10 opacity-40 text-sm">
                    { (reelComments[activeSheet.reelId] || []).length === 0 ? "No comments yet. Start the conversation!" : "You've reached the end." }
                  </div>
                </div>
                <div className="p-4 border-t dark:border-white/10 flex items-center gap-3 bg-white dark:bg-[#262626]">
                  <div className="w-8 h-8 rounded-full overflow-hidden shrink-0">
                    <img src={`https://api.dicebear.com/7.x/avataaars/svg?seed=${currentUser}`} alt="avatar" />
                  </div>
                  <input 
                    type="text" 
                    placeholder={`Add a comment...`}
                    value={commentText}
                    onChange={(e) => setCommentText(e.target.value)}
                    className="flex-1 bg-transparent text-sm focus:outline-none"
                    autoFocus
                  />
                  <button 
                    onClick={addComment}
                    disabled={!commentText.trim()}
                    className="text-[#0095F6] font-bold text-sm disabled:opacity-30"
                  >
                    Post
                  </button>
                </div>
              </div>
            )}

            {activeSheet.type === 'share' && (
              <div className="p-4 space-y-6">
                <div className="text-center font-bold">Share</div>
                <div className="flex gap-6 overflow-x-auto no-scrollbar pb-2">
                  {['cyber_punk', 'pixel_wizard', 'neon_knight'].map(user => (
                    <div key={user} className="flex flex-col items-center gap-1 shrink-0">
                      <div className="w-14 h-14 rounded-full overflow-hidden bg-gray-500/10">
                        <img src={`https://api.dicebear.com/7.x/avataaars/svg?seed=${user}`} alt="user" />
                      </div>
                      <span className="text-[11px] opacity-70">@{user}</span>
                    </div>
                  ))}
                </div>
                <div className="grid grid-cols-4 gap-4 pb-4">
                  <ShareOption icon="fa-copy" label="Copy Link" />
                  <ShareOption icon="fa-share-nodes" label="Share via..." />
                  <ShareOption icon="fa-paper-plane" label="Send in Chat" />
                  <ShareOption icon="fa-envelope" label="Email" />
                </div>
              </div>
            )}

            {activeSheet.type === 'more' && (
              <div className="pb-8">
                <MoreOption label="Report" color="text-[#ED4956]" />
                <MoreOption label="Not Interested" />
                <MoreOption label="Remix this reel" />
                <MoreOption label="Save" />
                <MoreOption label="Share to..." />
                <MoreOption label="Copy link" />
                <MoreOption label="Cancel" onClick={() => setActiveSheet(null)} border={false} />
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
};

const ReelAction = ({ icon, count, onClick, hideCount }: { icon: string; count: number; onClick?: () => void; hideCount?: boolean }) => (
  <div className="flex flex-col items-center gap-1">
    <button onClick={onClick} className="text-2xl drop-shadow-2xl transition-transform active:scale-125 hover:scale-110 text-white">
      <i className={icon}></i>
    </button>
    {!hideCount && <span className="text-[12px] font-bold drop-shadow-lg text-white">{count > 999 ? (count/1000).toFixed(1) + 'K' : count}</span>}
  </div>
);

const CommentItem = ({ comment }: { comment: PostComment }) => (
  <div className="flex gap-3">
    <div className="w-8 h-8 rounded-full overflow-hidden shrink-0">
      <img src={comment.avatar} alt="avatar" />
    </div>
    <div className="flex-1 space-y-1">
      <div className="text-sm">
        <span className="font-bold mr-2">{comment.user}</span>
        <span className="opacity-90">{comment.text}</span>
      </div>
      <div className="flex items-center gap-4 text-[12px] opacity-40">
        <span>{comment.time}</span>
        <button className="font-bold">Reply</button>
      </div>
    </div>
    <button className="text-[12px] opacity-40 self-start mt-1">
      <i className="fa-regular fa-heart"></i>
    </button>
  </div>
);

const ShareOption = ({ icon, label }: { icon: string, label: string }) => (
  <button className="flex flex-col items-center gap-2 group active:scale-95 transition-transform">
    <div className="w-12 h-12 rounded-full border dark:border-white/10 flex items-center justify-center text-xl group-hover:bg-gray-500/5 transition-colors">
      <i className={`fa-solid ${icon}`}></i>
    </div>
    <span className="text-[11px] opacity-70 text-center leading-tight">{label}</span>
  </button>
);

const MoreOption = ({ label, color, border = true, onClick }: { label: string, color?: string, border?: boolean, onClick?: () => void }) => (
  <button 
    onClick={onClick}
    className={`w-full py-3.5 text-center text-[14px] font-medium active:bg-gray-500/10 transition-colors ${color || ''} ${border ? 'border-b dark:border-white/5' : ''}`}
  >
    {label}
  </button>
);

export default ReelsFeed;
